# render.yaml
services:
  - type: web
    name: flask-license-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MONGODB_URL
        fromDatabase:
          name: my-mongo-db
          property: connectionString
